### ISSUE TITLE
npm audit report

### ISSUE THREAD

**Issue by juancarloselorriaga** [shahnawaz/react-native-barcode-mask#16]
I know this may not be an actual issue, but I consider important to report them.

![image](https://user-images.githubusercontent.com/34046056/67976970-c0f26a00-fbdc-11e9-8a6e-3e81b455fc52.png)

**Comment by shahnawaz** [comment]
@juancarloselorriaga 
Thanks for reporting this.

Would you be interested in looking why this happened?

**Comment by shahnawaz** [comment]
:tada: Audit report has been updated in version 1.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/react-native-barcode-mask/v/1.2.0)
- [GitHub release](https://github.com/shahnawaz/react-native-barcode-mask/releases/tag/v1.2.0)
