### ISSUE TITLE
QRCode is recognized outside of masks 

### ISSUE THREAD

**Issue by dudgns0908** [shahnawaz/react-native-barcode-mask#17]
Barcode is recognized only inside Mask. but QRCode is not..

How to solve?

**Comment by shahnawaz** [comment]
Hi @dudgns0908 ,

This package applies layout (styles) on top of RN Camera. To restrict the scanning area you might have look into RN Camera documentation.

**Comment by dudgns0908** [comment]
It is not working. 
I think RNCamera's orientation is fixed landscape.
