### ISSUE TITLE
CameraManager.checkIfRecordAudioPermissionsAreDefined

### ISSUE THREAD

**Issue by Tanererkan06** [shahnawaz/react-native-barcode-mask#18]
hi bro ,
i was given camera persmission on manifest but its still return this mistake .. how can be solve that 

CameraManager.checkIfRecordAudioPermissionsAreDefined is not a function. (In 'CameraManager.checkIfRecordAudioPermissionsAreDefined()', 'CameraManager.checkIfRecordAudioPermissionsAreDefined' is undefined)

**Comment by shahnawaz** [comment]
Hi @Tanererkan06,

While using RN Camera, you need to specify some permissions within your app to access camera. 

If you are still looking for a solution, please check this [doc](https://github.com/react-native-community/react-native-camera#permissions) on how to set permissions while using RN Camera.
