### ISSUE TITLE
useNativeDriver warning with react-native 0.62.X

### ISSUE THREAD

**Issue by fumiki** [shahnawaz/react-native-barcode-mask#22]
useNativeDriver of Animated is required option on react-native 0.62.X.
Could you consider passing the useNativeDriver option explicitly?

<img width="272" alt="screenshot 2020-04-24 21 40 08" src="https://user-images.githubusercontent.com/2100809/80214007-13d14980-8675-11ea-89d9-171f5bba0d8f.png">

**Comment by shahnawaz** [comment]
Hi @fumiki ,

Thanks, let me update it and get back to you here

**Comment by fumiki** [comment]
Great!! Thanks for the quick fix! 🙏✨
