### ISSUE TITLE
zIndex makes outer mask not visible

### ISSUE THREAD

**Issue by marcoskubis** [shahnawaz/react-native-barcode-mask#27]
https://github.com/shahnawaz/react-native-barcode-mask/blob/8be8bfd073ebb3a502c89d48d4e3e388b6082740/index.js#L43

I don't know if this `zIndex: -1` is important, but I'm trying to get the outer mask appear and the `zIndex: -1` is making the outer mask be invisible. I think the `zIndex: -1 `is pushing the outer mask to back of camera view.

![image](https://user-images.githubusercontent.com/3844716/81356923-bf808d80-90a8-11ea-9acc-9ac52a8122b2.png)

When I remove that line, it works!

![image](https://user-images.githubusercontent.com/3844716/81356953-d7f0a800-90a8-11ea-8141-1e96988e7433.png)

Am I doing something wrong?

**Comment by pixelize** [comment]
Same problem, removing zIndex: -1 makes it work !
