### ISSUE TITLE
How to stop animation Immediately when mask size change?

### ISSUE THREAD

**Issue by zhangqiangoffice** [shahnawaz/react-native-barcode-mask#4]
There is a memory leak. After the Mask unmount, the onComplete animation is still to run and run...

**Comment by shahnawaz** [comment]
Hi @zhangqiangoffice ,

Thank you for finding this out. :)

Let me look into it and update it.

**Comment by shahnawaz** [comment]
Closing the issue (fixed).

Thanks @zhangqiangoffice for the PR
