### ISSUE TITLE
Edges pushed behind the overlay when size increased

### ISSUE THREAD

**Issue by joshidipesh12** [shahnawaz/react-native-barcode-mask#49]
The edges of the default marker are pushed behing the semi-transparent overlay when their size and radius is increased making the overall component look wierd.
![Screenshot_1624188732](https://user-images.githubusercontent.com/66198105/122672517-7aa2b200-d1e9-11eb-9e25-748b3b36fb60.png)

**Comment by Yuliia143** [comment]
@joshidipesh12
Hi, I have the same issue, but your solution doesn't work for me. Did you change anything else?

**Comment by anhquan291** [comment]
I'm facing the same issue. Any helps please. Thanks a lot

**Comment by Bryceacampbell** [comment]
#56 I have a fix for this here

**Comment by joshidipesh12** [comment]
Thanks @Bryceacampbell 🎀👌
