### ISSUE TITLE
Question: How to restrict scanning area using this mask?

### ISSUE THREAD

**Issue by anniewey** [shahnawaz/react-native-barcode-mask#7]
I'm using Google Vision to scan for barcodes in Android, however I'm unable to limit the scan boundary to this mask

**Comment by neilzhengzx** [comment]
+1

**Comment by slavikdenis** [comment]
I don't think that this library should take care of that. You have to implement that yourself.

**Comment by anniewey** [comment]
@slavikdenis Right, I have to opt for other library for this function. This library only renders an overlay UI.

**Comment by jbburf** [comment]
What package did you use @slavikdenis to control the scan area?

**Comment by slavikdenis** [comment]
I did my own implementation and used `@react-native-community/image-editor` to crop the needed area out of the whole picture taken and worked with that.
