### ISSUE TITLE
Not supported on BLU smartphone

### ISSUE THREAD

**Issue by lucasgouvea** [shahnawaz/react-native-barcode-mask#8]
Tested the component on MotoG4, Samsung and BLU Studio Mega. Didn't work only on BLU device.

BLU products: https://bluproducts.com/home/
BLU Studio Mega: https://www.gsmarena.com/blu_studio_mega-8709.php

**Comment by shahnawaz** [comment]
@lucasgouvea This is strange, because this library is simply a UI layer and it will be visible on all platforms where React Native is runnable. Are you able to run React Native apps on those mobile?

**Comment by lucasgouvea** [comment]
Sorry, the issue is on RNCamera.
