### ISSUE TITLE
Custom mask background color

### ISSUE THREAD

**Issue by iwashi1t** [shahnawaz/react-native-barcode-mask#9]
Could you make it possible to specify a mask background color other than black?

e.g.) `rgba(0.0,0.5,0.3,0.6)`

Thank you.

**Comment by shahnawaz** [comment]
That is a good idea, we can surely do something like this.

Let me see if I can do it over the weekend.

**Comment by prodoxx** [comment]
Hey @shahnawaz . Thanks for the awesome code. Were you able to get this done? Would be great to know if you did it or else I'll probably fork this and do it myself.

**Comment by shahnawaz** [comment]
Hey @prodoxx, apologies as I was not able to look into it.

If you could do this and send a PR, I would gladly merge it today (or whenever you send it).

Really appreciate it. Thanks!

**Comment by shahnawaz** [comment]
Solved: https://github.com/shahnawaz/react-native-barcode-mask/pull/12
